const fs=require('fs');
const assert=require('assert');
const root='/mnt/data/progress-v2-stable-work';
const sync=fs.readFileSync(root+'/js/progress-sync.js','utf8');
const html=fs.readFileSync(root+'/index.html','utf8');
assert(html.includes('class="modern-sidebar"'),'Simulator must expose .modern-sidebar');
assert(sync.includes("document.querySelector('.modern-sidebar')"),'Progress Sync tab must target .modern-sidebar');
assert(!sync.includes("document.querySelector('.menu-tabs')"),'Broken .menu-tabs target must not return');
assert(!sync.includes('new MutationObserver('),'Progress Sync boot must not install unbounded whole-document MutationObserver');
assert(sync.includes('[250,1000,2500].forEach'),'Progress Sync surface boot should use bounded retries');
assert(sync.includes('requestIdleCallback'),'Startup cloud reconciliation should be deferred until browser idle when available');
assert(sync.includes("insertBefore(t,settings)"),'Progress Sync tab should insert before Settings when available');
console.log('PASS Progress Sync V2 UI boot regression: correct sidebar target, no recursive observer');
